[package]
name = "classifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
clap = { version = "3.2.8", features = ["derive"] }
petgraph = "0.6.2"
regex = "1.5.5"
